[package]
name = "zkbytecode_executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
serde = "1.0"
serde_json = { version = "1.0.66", features = ["unbounded_depth"] }
serde_derive = "1.0"
ethers = { version = "2.0.7", features = ["ethers-solc"] }
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }
url = "2.2.2"
pretty_assertions = "1.0.0"
log = "0.4.14"
env_logger = "0.9"
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_04_20" }
rand_chacha = "0.3"
paste = "1.0"
rand_xorshift = "0.3.0"
rand_core = "0.6.4"

bus-mapping = { path = "../zkevm-circuits/bus-mapping", features = ["test"] }
eth-types = { path = "../zkevm-circuits/eth-types" }
zkevm-circuits = { path = "../zkevm-circuits/zkevm-circuits", features = [
	"test-circuits",
] }
mock = { path = "../zkevm-circuits/mock" }
